# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Accessibility Initiative (WAI)
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter:
  username: w3c_wai
author: w3c_wai
includes_dir: _external/wai-website-jekyll-templates/_includes
layouts_dir: _external/wai-website-jekyll-templates/_layouts
exclude:
  - "_external"
# Build settings
markdown: kramdown
kramwdown:
  - toc_levels: "2,3"
repository: w3c/wai-resource-template

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links

relative_links:
  -  enabled:     true
  -  collections: true

exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"